/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import {
  Color,
  DoubleSide,
  Mesh,
  MeshPhysicalMaterialProperties,
  Object3D,
  Object3DEventMap,
} from "three";
import { useFrame } from "@react-three/fiber";
const meshProperties: Partial<MeshPhysicalMaterialProperties> = {
  // transparent: true,
  // opacity: 0.85,
  transparent: true,
  opacity: 0.8,
  color: new Color(230, 112, 137),
  roughness: 0.25,
  metalness: 0.9,
  reflectivity: 0.85,
  visible: true,
  iridescence: 0.4,
  fog: true,
  depthTest: true,
  depthWrite: true,
  side: DoubleSide,
};
const nodeIsMesh = (node?: Object3D<Object3DEventMap>): node is Mesh =>
  node?.type === "Mesh";
export function Model() {
  const { nodes } = useGLTF("name-mesh-3/25_12_19_04_54_45_186.gltf");
  const area1 = nodes["Area_(1)"];
  const meshRef = useRef<Mesh>(undefined);

  const material = <meshPhysicalMaterial {...meshProperties} />;

  //   useFrame((state, delta) => {
  //     if (meshRef?.current != null) {
  //       meshRef.current.rotation.z += delta / 2;

  //     //   meshRef.current.rotation.y += delta / 2;

  //       meshRef.current.rotation.x += delta / 2;
  //     }
  //   });

  return (
    <group
      dispose={null}
      position={[0, 0, -900]}
      rotation={[0, -Math.PI / 2, 0]}
    >
      {[area1].map((area) => (
        <mesh
          castShadow
          receiveShadow
          geometry={nodeIsMesh(area) ? area.geometry : undefined}
          ref={meshRef}
        >
          {material}
        </mesh>
      ))}
    </group>
  );
}

useGLTF.preload("name-mesh-2/25_12_18_05_13_51_832.gltf");
